# Generated by Django 5.0.2 on 2024-02-20 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='searchapp.anime'),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='animerating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
