# Generated by Django 5.0.2 on 2024-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_remove_animerating_anime_remove_animerating_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='id',
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(default=999999999, primary_key=True, serialize=False, unique=True),
        ),
    ]
