# Generated by Django 5.0.2 on 2024-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_remove_anime_id_alter_anime_anime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
