# Generated by Django 5.0.2 on 2024-02-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_anime_id_alter_anime_anime_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
