# Generated by Django 5.0.2 on 2024-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_alter_anime_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='members',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
