# Generated by Django 5.0.2 on 2024-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0008_alter_anime_members_alter_anime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerating',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
